### ISSUE TITLE
Latest 3.0 build breaks actions

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-denon-recorder#12]
@istnv 

In the lastest 3.0 beta the module connects but none of theactions will work.  When I select initiate recording or one touch record a "recording control" greyed out text box appears where there used to be only one dropdown box.  The text is greyed out and says "unknown type text"  Screenshot attached.  This appears to happen with any action selected not just recording.
![Screenshot 2023-05-18 160453](https://github.com/bitfocus/companion-module-denon-recorder/assets/51127807/87e128e4-44bd-4020-b923-7262b09ff178)

**Comment by obcocav** [comment]
Meant to add that the instance shows connected but even feedback doesn't work either when started manually.

**Comment by istnv** [comment]
I'll take a look when I can. I do not have any hardware to test with so it's kind of a shot in the dark :)
I do know where to look when I have time so it should not take me too long.

**Comment by obcocav** [comment]
Whatever I can do to help just let me know!  Thank you!Sent from my iPhoneOn May 18, 2023, at 16:37, John Knight Jr ***@***.***> wrote:﻿
I'll take a look when I can. I do not have any hardware to test with so it's kind of a shot in the dark :)

**Comment by obcocav** [comment]
@istnv .  Not sure its helpful since it was obviously right before the rewrite but I went back to build 5797 and it works as expected.  There is the "Recording Control" header but not dropdown or text box there at all FWIW.

![recorder problem2](https://github.com/bitfocus/companion-module-denon-recorder/assets/51127807/a2c69bae-825b-4331-8b2f-d525326df751)

**Comment by obcocav** [comment]
"Error; Socket not connected." is the error in the module log.

**Comment by istnv** [comment]
Fix should be in the next rebuild.

**Comment by obcocav** [comment]
Awesome!  Thanks again so much for what y’all do!Sent from my iPhoneOn May 18, 2023, at 17:36, John Knight Jr ***@***.***> wrote:﻿
Fix should be in the next rebuild.

**Comment by obcocav** [comment]
@istnv .  Tried out the build this morning and the actions work but none of the feedbacks are working.  Looked at the console but nothing shows up there as far as errors or anything.  Let me know if I can help diagnose.

Thanks!

**Comment by istnv** [comment]
@obcocav Try the next build

**Comment by istnv** [comment]
@obcocav Has this been tested, yet?

**Comment by obcocav** [comment]
Yes it has!  Sorry forgot to update.  All seems well now.  Thank you!Sent from my iPhoneOn May 31, 2023, at 21:19, John Knight Jr ***@***.***> wrote:﻿
@obcocav Has this been tested, yet?
