### ISSUE TITLE
Denon DN900R

### ISSUE THREAD

**Issue by McHauge** [bitfocus/companion-module-denon-recorder#2]
From Facebook:
Posted by Kevin Haddock.

Hey guys.

Looking to control a Denon DN900R audio recorder via a Streamdeck and companion. I found the manual that talks about up control and serial control but a little lost as to how to translate this into useable action. Really only looking to start and stop recording.

Any ideas on how to get this done or where to start?

Thanks

https://09f3b4e35b829ef5e143-525d2f2124a3483dfbd3f17c87329990.ssl.cf2.rackcdn.com/1934/documents/DN-900R-SerialCommandProtocolGuide-v1.0r.pdf?fbclid=IwAR0LyVMIU1i6-2kK0G3QBO1OmRFxO4EWTbv46NLEQ_3X4eBn954BlO6nx2M

https://09f3b4e35b829ef5e143-525d2f2124a3483dfbd3f17c87329990.ssl.cf2.rackcdn.com/1934/documents/DN-900R-UserGuide-v1.0.pdf?fbclid=IwAR0IWv7yW60y20RuLLc3VqU2sMJb1WA63zIWh3ggfrMxkb8OPvq9-Kl57cM

**Comment by istnv** [comment]
This can be closed now that the module is in core. Any new problems should open a new issue.
