### ISSUE TITLE
Denon Recorder module showing no feedback in 2.2.0

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-denon-recorder#4]
@istnv 

The latest 2.2.0 build has lost feedback for the Denon Recorder module.  It is available in 2.1.2 but does not show up in the feedback list on beta build.

Let me know if I can help in any way.

Thanks!

**Comment by obcocav** [comment]
Just downloaded the RGB fix version.  Still not working.  Sorry if I'm misunderstanding how this process works.  Thanks to all who work on these projects!

**Comment by istnv** [comment]
Which version did you download?

**Comment by obcocav** [comment]
https://bitfocus.io/companion/download/build/companion-2.2.0-6fb54e5-2876-mac.dmg

![A1AF84B1-01BF-4D16-A7F6-4CF42B706FA2](https://user-images.githubusercontent.com/51127807/108080941-0509b800-7036-11eb-871e-39413fd9e5e8.jpeg)

**Comment by istnv** [comment]
That one should work. I'll download and see if I can figure it out. I don't have an actual recorder to test.

**Comment by obcocav** [comment]
@istnv   Hey John.  Just tried it again by re-adding the instance instead of using the one I already had and it seemed to work!  Don't have the recorder accessible right now due to the winter storm but I'll try it out ASAP and get back.  Thank you!!

**Comment by istnv** [comment]
Thanks for responding. I don't see anything wrong here.
